# 数据操作与预处理

本notebook涵盖深度学习的基础数据操作技能:
- 张量(Tensor)的创建、操作和运算
- 使用Pandas进行数据预处理
- 数据格式转换

这些是深度学习的基本技能,所有后续章节都会用到。

## 第一部分: 张量数据操作

### 1.1 张量简介

张量(tensor)是深度学习框架的核心数据结构。它是一个$n$维数组,可以在GPU上加速计算,并支持自动微分。

- 1维张量 = 向量(vector)
- 2维张量 = 矩阵(matrix)  
- 3维及以上张量 = 高维张量

首先导入PyTorch库:

In [1]:
import torch

### 1.2 创建张量

**创建行向量**

In [2]:
# 使用 arange 创建一个包含0到11的行向量
x = torch.arange(12)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

**查看张量的形状和元素总数**

In [3]:
# 查看张量形状
print("形状:", x.shape)

# 查看元素总数
print("元素总数:", x.numel())

形状: torch.Size([12])
元素总数: 12


**改变张量形状**

In [4]:
# 将形状从(12,)改为(3, 4)
X = x.reshape(3, 4)
print(X)

# 使用-1自动计算维度
X_auto = x.reshape(-1, 4)  # 自动计算为3行
print("\n自动计算维度:")
print(X_auto)

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

自动计算维度:
tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])


In [5]:
# 自动计算列为 4 列
X_auto_2 = x.reshape(3, -1)
print(X_auto_2)

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])


In [6]:
# 自动计算一个中间的维度
X_auto_3 = x.reshape(2, -1, 3)
print(X_auto_3)

tensor([[[ 0,  1,  2],
         [ 3,  4,  5]],

        [[ 6,  7,  8],
         [ 9, 10, 11]]])


**创建特殊张量**

In [7]:
# 全0张量
zeros = torch.zeros((2, 3, 4))
print("全0张量:")
print(zeros)

# 全1张量
ones = torch.ones((2, 3, 4))
print("\n全1张量:")
print(ones)

# 随机张量(标准正态分布) torch.randn()
random_tensor = torch.randn((3, 4))
print("\n随机张量:")
print(random_tensor)

# 随机张量 torch.rand()
rand_2 = torch.rand(3, 4)
print("\n随机张量 2 :", rand_2)

# 从Python列表创建张量
tensor_from_list = torch.tensor([[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
print("\n从列表创建:")
print(tensor_from_list)

全0张量:
tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

全1张量:
tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

随机张量:
tensor([[-0.7895, -1.0582, -0.6220,  0.3434],
        [ 0.7170, -0.4214, -2.0597,  0.9780],
        [-0.0859, -0.3706, -1.6641, -0.1410]])

随机张量 2 : tensor([[0.2720, 0.0545, 0.5012, 0.2595],
        [0.5243, 0.8454, 0.7863, 0.7719],
        [0.6186, 0.5684, 0.4676, 0.5497]])

从列表创建:
tensor([[2, 1, 4, 3],
        [1, 2, 3, 4],
        [4, 3, 2, 1]])


### 1.3 张量运算

**按元素运算**

In [8]:
x = torch.tensor([1.0, 2, 4, 8])
y = torch.tensor([2, 2, 2, 2])

print("加法:", x + y)
print("减法:", x - y)
print("乘法:", x * y)
print("除法:", x / y)
print("幂运算:", x ** y)
print("指数运算:", torch.exp(x))

加法: tensor([ 3.,  4.,  6., 10.])
减法: tensor([-1.,  0.,  2.,  6.])
乘法: tensor([ 2.,  4.,  8., 16.])
除法: tensor([0.5000, 1.0000, 2.0000, 4.0000])
幂运算: tensor([ 1.,  4., 16., 64.])
指数运算: tensor([2.7183e+00, 7.3891e+00, 5.4598e+01, 2.9810e+03])


**矩阵运算**

In [9]:
# 张量拼接
X = torch.arange(12, dtype=torch.float32).reshape((3,4))
Y = torch.tensor([
    [2.0, 1, 4, 3],
    [1, 2, 3, 4],
    [4, 3, 2, 1]
])

print("原张量X:")
print(X)
print("\n原张量Y:")
print(Y)

# 按行拼接(沿着第0维)
print("\n按行拼接:")
print(torch.cat((X, Y), dim=0))

# 按列拼接(沿着第1维)
print("\n按列拼接:")
print(torch.cat((X, Y), dim=1))

原张量X:
tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

原张量Y:
tensor([[2., 1., 4., 3.],
        [1., 2., 3., 4.],
        [4., 3., 2., 1.]])

按行拼接:
tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [ 2.,  1.,  4.,  3.],
        [ 1.,  2.,  3.,  4.],
        [ 4.,  3.,  2.,  1.]])

按列拼接:
tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
        [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
        [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]])


**逻辑运算**

In [10]:
# 通过逻辑运算构建二元张量
print("X == Y:")
print(X == Y)

X == Y:
tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])


**求和与统计**

In [11]:
# 所有元素求和
print("所有元素的和:", X.sum())

# 其他统计函数
print("平均值:", X.mean())
print("最大值:", X.max())
print("最小值:", X.min())

所有元素的和: tensor(66.)
平均值: tensor(5.5000)
最大值: tensor(11.)
最小值: tensor(0.)


### 1.4 索引和切片

In [12]:
# 访问单个元素
print("最后一行:", X[-1])
print("第2行第3列:", X[1, 2])

# 切片访问
print("\n第2-3行,第1-3列:")
print(X[1:3, 0:3])

# 修改元素
X[1, 2] = 9
print("\n修改后的X:")
print(X)

# 修改多个元素
X[0:2, :] = 12
print("\n批量修改后的X:")
print(X)

最后一行: tensor([ 8.,  9., 10., 11.])
第2行第3列: tensor(6.)

第2-3行,第1-3列:
tensor([[ 4.,  5.,  6.],
        [ 8.,  9., 10.]])

修改后的X:
tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  9.,  7.],
        [ 8.,  9., 10., 11.]])

批量修改后的X:
tensor([[12., 12., 12., 12.],
        [12., 12., 12., 12.],
        [ 8.,  9., 10., 11.]])


### 1.5 内存管理与运算

In [13]:
# 查看内存地址
before = id(Y)
Y = Y + X
print("内存地址改变:", id(Y) != before)

# 原地操作(不分配新内存)
Z = torch.zeros_like(Y)
print("原地操作前ID:", id(Z))
Z[:] = X + Y
print("原地操作后ID:", id(Z))

# 使用 += 等操作也是原地的
before = id(X)
X += Y
print("\n使用+=后ID不变:", id(X) == before)

内存地址改变: True
原地操作前ID: 139090835224000
原地操作后ID: 139090835224000

使用+=后ID不变: True


### 1.6 与其他Python对象的转换

In [14]:
# 转换为NumPy数组
A = X.numpy()
print("NumPy数组:")
print(type(A))
print(A)

# 从NumPy数组转换为张量
B = torch.tensor(A)
print("\n转回张量:")
print(type(B))

# 标量张量转换为Python数值
a = torch.tensor([3.5])
print("\n标量张量:", a, a.item(), type(a.item()))

NumPy数组:
<class 'numpy.ndarray'>
[[26. 25. 28. 27.]
 [25. 26. 27. 28.]
 [20. 21. 22. 23.]]

转回张量:
<class 'torch.Tensor'>

标量张量: tensor([3.5000]) 3.5 <class 'float'>


### 1.7 广播机制

In [15]:
# 不同形状的张量可以通过广播机制进行运算
a = torch.arange(3).reshape((3, 1))
b = torch.arange(2).reshape((1, 2))

print("a的形状:", a.shape)
print(a)
print("\nb的形状:", b.shape)
print(b)

print("\na + b (广播机制):")
print(a + b)

# 可以看到，它是将两个矩阵维度扩展后相加

a的形状: torch.Size([3, 1])
tensor([[0],
        [1],
        [2]])

b的形状: torch.Size([1, 2])
tensor([[0, 1]])

a + b (广播机制):
tensor([[0, 1],
        [1, 2],
        [2, 3]])


---

## 第二部分: 数据预处理

### 2.1 使用Pandas处理表格数据

在实际项目中,我们经常需要处理CSV、Excel等格式的原始数据。Pandas是Python中最常用的数据分析工具。

In [16]:
import os
import pandas as pd

### 2.2 创建和读取数据集

In [17]:
# 创建数据目录
os.makedirs(os.path.join('..', 'data'), exist_ok=True)
data_file = os.path.join('..', 'data', 'house_tiny.csv')

# 写入CSV文件
with open(data_file, 'w') as f:
    f.write('NumRooms,Alley,Price\n')  # 列名
    f.write('NA,Pave,127500\n')  # 每行表示一个数据样本
    f.write('2,NA,106000\n')
    f.write('4,NA,178100\n')
    f.write('NA,NA,140000\n')

print("CSV文件已创建")

CSV文件已创建


In [18]:
# 读取CSV文件
data = pd.read_csv(data_file)
print("原始数据:")
print(data)

原始数据:
   NumRooms Alley   Price
0       NaN  Pave  127500
1       2.0   NaN  106000
2       4.0   NaN  178100
3       NaN   NaN  140000


### 2.3 处理缺失值

真实数据经常包含缺失值(NaN)。常见的处理方法:
- **插值法**: 用其他值(如均值)填充
- **删除法**: 删除含缺失值的行或列

In [19]:
# 将数据分为输入和输出
inputs, outputs = data.iloc[:, 0:2], data.iloc[:, 2]

# 用均值填充数值列的缺失值
# inputs = inputs.fillna(inputs.mean())  # 报错，数据类型问题！fixed

# 用均值填充数值列的缺失值，并使用numeric_only=True确保只对数值列进行操作
# 非数值列的缺失值（如'Alley'列）将保留，后续由pd.get_dummies处理
inputs = inputs.fillna(inputs.mean(numeric_only=True))

print("填充后的inputs:")
print(inputs)

填充后的inputs:
   NumRooms Alley
0       3.0  Pave
1       2.0   NaN
2       4.0   NaN
3       3.0   NaN


### 2.4 处理类别数据

对于类别特征,我们使用独热编码(one-hot encoding)将其转换为数值。

In [20]:
# 对类别列进行独热编码
inputs = pd.get_dummies(inputs, dummy_na=True)
print("独热编码后的inputs:")
print(inputs)

独热编码后的inputs:
   NumRooms  Alley_Pave  Alley_nan
0       3.0        True      False
1       2.0       False       True
2       4.0       False       True
3       3.0       False       True


### 2.5 转换为张量格式

In [21]:
# 将处理好的数据转换为张量
X = torch.tensor(inputs.to_numpy(dtype=float))
y = torch.tensor(outputs.to_numpy(dtype=float))

print("特征张量X:")
print(X)
print("\n标签张量y:")
print(y)

特征张量X:
tensor([[3., 1., 0.],
        [2., 0., 1.],
        [4., 0., 1.],
        [3., 0., 1.]], dtype=torch.float64)

标签张量y:
tensor([127500., 106000., 178100., 140000.], dtype=torch.float64)


---

## 小结

本notebook介绍了深度学习中最基础的数据操作技能:

### 张量操作
- 张量的创建: `torch.arange()`, `torch.zeros()`, `torch.ones()`, `torch.randn()`
- 张量属性: `.shape`, `.numel()`
- 形状变换: `.reshape()`
- 基本运算: 加减乘除、幂运算、指数等
- 索引切片: 访问和修改张量元素
- 拼接操作: `torch.cat()`
- 广播机制: 不同形状张量的自动对齐

### 数据预处理
- 使用Pandas读写CSV文件
- 处理缺失值: `.fillna()`
- 独热编码: `pd.get_dummies()`
- Pandas与Tensor互转: `.to_numpy()`, `torch.tensor()`

## 练习

1. 创建一个5×5的随机矩阵,计算它的转置和行列式
2. 实现一个函数,将摄氏温度数组转换为华氏温度
3. 创建包含更多行和列的数据集:
   - 删除缺失值最多的列
   - 将预处理后的数据集转换为张量格式
4. 尝试使用广播机制,对一个矩阵的每一行减去该行的均值