# 数据操作与预处理

本notebook涵盖深度学习的基础数据操作技能:
- 张量(Tensor)的创建、操作和运算
- 使用Pandas进行数据预处理
- 数据格式转换

这些是深度学习的基本技能,所有后续章节都会用到。

## 第一部分: 张量数据操作

### 1.1 张量简介

张量(tensor)是深度学习框架的核心数据结构。它是一个$n$维数组,可以在GPU上加速计算,并支持自动微分。

- 1维张量 = 向量(vector)
- 2维张量 = 矩阵(matrix)  
- 3维及以上张量 = 高维张量

首先导入PyTorch库:

In [1]:
import torch

### 1.2 创建张量

**创建行向量**

In [2]:
# 使用 arange 创建一个包含0到11的行向量
x = torch.arange(12)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

**查看张量的形状和元素总数**

In [3]:
# 查看张量形状
print("形状:", x.shape)

# 查看元素总数
print("元素总数:", x.numel())

形状: torch.Size([12])
元素总数: 12


**改变张量形状**

In [4]:
# 将形状从(12,)改为(3, 4)
X = x.reshape(3, 4)
print(X)

# 使用-1自动计算维度
X_auto = x.reshape(-1, 4)  # 自动计算为3行
print("\n自动计算维度:")
print(X_auto)

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

自动计算维度:
tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])


**创建特殊张量**

In [5]:
# 全0张量
zeros = torch.zeros((2, 3, 4))
print("全0张量:")
print(zeros)

# 全1张量
ones = torch.ones((2, 3, 4))
print("\n全1张量:")
print(ones)

# 随机张量(标准正态分布)
random_tensor = torch.randn((3, 4))
print("\n随机张量:")
print(random_tensor)

# 从Python列表创建张量
tensor_from_list = torch.tensor([[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
print("\n从列表创建:")
print(tensor_from_list)

全0张量:
tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

全1张量:
tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

随机张量:
tensor([[-0.4343,  1.1135, -0.5877,  0.2350],
        [ 0.2778, -0.3186,  0.0937, -0.1927],
        [ 0.2525, -1.1877,  0.3721, -0.5777]])

从列表创建:
tensor([[2, 1, 4, 3],
        [1, 2, 3, 4],
        [4, 3, 2, 1]])


### 1.3 张量运算

**按元素运算**

In [6]:
x = torch.tensor([1.0, 2, 4, 8])
y = torch.tensor([2, 2, 2, 2])

print("加法:", x + y)
print("减法:", x - y)
print("乘法:", x * y)
print("除法:", x / y)
print("幂运算:", x ** y)
print("指数运算:", torch.exp(x))

加法: tensor([ 3.,  4.,  6., 10.])
减法: tensor([-1.,  0.,  2.,  6.])
乘法: tensor([ 2.,  4.,  8., 16.])
除法: tensor([0.5000, 1.0000, 2.0000, 4.0000])
幂运算: tensor([ 1.,  4., 16., 64.])
指数运算: tensor([2.7183e+00, 7.3891e+00, 5.4598e+01, 2.9810e+03])


**矩阵运算**

In [7]:
# 张量拼接
X = torch.arange(12, dtype=torch.float32).reshape((3,4))
Y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])

print("原张量X:")
print(X)
print("\n原张量Y:")
print(Y)

# 按行拼接(沿着第0维)
print("\n按行拼接:")
print(torch.cat((X, Y), dim=0))

# 按列拼接(沿着第1维)
print("\n按列拼接:")
print(torch.cat((X, Y), dim=1))

原张量X:
tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

原张量Y:
tensor([[2., 1., 4., 3.],
        [1., 2., 3., 4.],
        [4., 3., 2., 1.]])

按行拼接:
tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [ 2.,  1.,  4.,  3.],
        [ 1.,  2.,  3.,  4.],
        [ 4.,  3.,  2.,  1.]])

按列拼接:
tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
        [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
        [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]])


**逻辑运算**

In [8]:
# 通过逻辑运算构建二元张量
print("X == Y:")
print(X == Y)

X == Y:
tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])


**求和与统计**

In [9]:
# 所有元素求和
print("所有元素的和:", X.sum())

# 其他统计函数
print("平均值:", X.mean())
print("最大值:", X.max())
print("最小值:", X.min())

所有元素的和: tensor(66.)
平均值: tensor(5.5000)
最大值: tensor(11.)
最小值: tensor(0.)


### 1.4 索引和切片

In [10]:
# 访问单个元素
print("最后一行:", X[-1])
print("第2行第3列:", X[1, 2])

# 切片访问
print("\n第2-3行,第1-3列:")
print(X[1:3, 0:3])

# 修改元素
X[1, 2] = 9
print("\n修改后的X:")
print(X)

# 修改多个元素
X[0:2, :] = 12
print("\n批量修改后的X:")
print(X)

最后一行: tensor([ 8.,  9., 10., 11.])
第2行第3列: tensor(6.)

第2-3行,第1-3列:
tensor([[ 4.,  5.,  6.],
        [ 8.,  9., 10.]])

修改后的X:
tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  9.,  7.],
        [ 8.,  9., 10., 11.]])

批量修改后的X:
tensor([[12., 12., 12., 12.],
        [12., 12., 12., 12.],
        [ 8.,  9., 10., 11.]])


### 1.5 内存管理与运算

In [11]:
# 查看内存地址
before = id(Y)
Y = Y + X
print("内存地址改变:", id(Y) != before)

# 原地操作(不分配新内存)
Z = torch.zeros_like(Y)
print("原地操作前ID:", id(Z))
Z[:] = X + Y
print("原地操作后ID:", id(Z))

# 使用 += 等操作也是原地的
before = id(X)
X += Y
print("\n使用+=后ID不变:", id(X) == before)

内存地址改变: True
原地操作前ID: 138857851087328
原地操作后ID: 138857851087328

使用+=后ID不变: True


### 1.6 与其他Python对象的转换

In [12]:
# 转换为NumPy数组
A = X.numpy()
print("NumPy数组:")
print(type(A))
print(A)

# 从NumPy数组转换为张量
B = torch.tensor(A)
print("\n转回张量:")
print(type(B))

# 标量张量转换为Python数值
a = torch.tensor([3.5])
print("\n标量张量:", a, a.item(), type(a.item()))

NumPy数组:
<class 'numpy.ndarray'>
[[26. 25. 28. 27.]
 [25. 26. 27. 28.]
 [20. 21. 22. 23.]]

转回张量:
<class 'torch.Tensor'>

标量张量: tensor([3.5000]) 3.5 <class 'float'>


### 1.7 广播机制

In [13]:
# 不同形状的张量可以通过广播机制进行运算
a = torch.arange(3).reshape((3, 1))
b = torch.arange(2).reshape((1, 2))

print("a的形状:", a.shape)
print(a)
print("\nb的形状:", b.shape)
print(b)

print("\na + b (广播机制):")
print(a + b)

a的形状: torch.Size([3, 1])
tensor([[0],
        [1],
        [2]])

b的形状: torch.Size([1, 2])
tensor([[0, 1]])

a + b (广播机制):
tensor([[0, 1],
        [1, 2],
        [2, 3]])


---

## 第二部分: 数据预处理

### 2.1 使用Pandas处理表格数据

在实际项目中,我们经常需要处理CSV、Excel等格式的原始数据。Pandas是Python中最常用的数据分析工具。

In [14]:
import os
import pandas as pd

### 2.2 创建和读取数据集

In [15]:
# 创建数据目录
os.makedirs(os.path.join('..', 'data'), exist_ok=True)
data_file = os.path.join('..', 'data', 'house_tiny.csv')

# 写入CSV文件
with open(data_file, 'w') as f:
    f.write('NumRooms,Alley,Price\n')  # 列名
    f.write('NA,Pave,127500\n')  # 每行表示一个数据样本
    f.write('2,NA,106000\n')
    f.write('4,NA,178100\n')
    f.write('NA,NA,140000\n')

print("CSV文件已创建")

CSV文件已创建


In [16]:
# 读取CSV文件
data = pd.read_csv(data_file)
print("原始数据:")
print(data)

原始数据:
   NumRooms Alley   Price
0       NaN  Pave  127500
1       2.0   NaN  106000
2       4.0   NaN  178100
3       NaN   NaN  140000


### 2.3 处理缺失值

真实数据经常包含缺失值(NaN)。常见的处理方法:
- **插值法**: 用其他值(如均值)填充
- **删除法**: 删除含缺失值的行或列

In [18]:
# 将数据分为输入和输出
inputs, outputs = data.iloc[:, 0:2], data.iloc[:, 2]

# 用均值填充数值列的缺失值

# inputs = inputs.fillna(inputs.mean()) # 报错了，数据类型不匹配，因为有非数值
# 修改为
# 用均值填充数值列的缺失值，并使用numeric_only=True确保只对数值列进行操作
# 非数值列的缺失值（如'Alley'列）将保留，后续由pd.get_dummies处理
inputs = inputs.fillna(inputs.mean(numeric_only=True))


print("填充后的inputs:")
print(inputs)

填充后的inputs:
   NumRooms Alley
0       3.0  Pave
1       2.0   NaN
2       4.0   NaN
3       3.0   NaN


### 2.4 处理类别数据

对于类别特征,我们使用独热编码(one-hot encoding)将其转换为数值。

In [19]:
# 对类别列进行独热编码
inputs = pd.get_dummies(inputs, dummy_na=True)
print("独热编码后的inputs:")
print(inputs)

独热编码后的inputs:
   NumRooms  Alley_Pave  Alley_nan
0       3.0        True      False
1       2.0       False       True
2       4.0       False       True
3       3.0       False       True


### 2.5 转换为张量格式

In [20]:
# 将处理好的数据转换为张量
X = torch.tensor(inputs.to_numpy(dtype=float))
y = torch.tensor(outputs.to_numpy(dtype=float))

print("特征张量X:")
print(X)
print("\n标签张量y:")
print(y)

特征张量X:
tensor([[3., 1., 0.],
        [2., 0., 1.],
        [4., 0., 1.],
        [3., 0., 1.]], dtype=torch.float64)

标签张量y:
tensor([127500., 106000., 178100., 140000.], dtype=torch.float64)


---

## 小结

本notebook介绍了深度学习中最基础的数据操作技能:

### 张量操作
- 张量的创建: `torch.arange()`, `torch.zeros()`, `torch.ones()`, `torch.randn()`
- 张量属性: `.shape`, `.numel()`
- 形状变换: `.reshape()`
- 基本运算: 加减乘除、幂运算、指数等
- 索引切片: 访问和修改张量元素
- 拼接操作: `torch.cat()`
- 广播机制: 不同形状张量的自动对齐

### 数据预处理
- 使用Pandas读写CSV文件
- 处理缺失值: `.fillna()`
- 独热编码: `pd.get_dummies()`
- Pandas与Tensor互转: `.to_numpy()`, `torch.tensor()`

## 练习

1. 创建一个5×5的随机矩阵,计算它的转置和行列式
2. 实现一个函数,将摄氏温度数组转换为华氏温度
3. 创建包含更多行和列的数据集:
   - 删除缺失值最多的列
   - 将预处理后的数据集转换为张量格式
4. 尝试使用广播机制,对一个矩阵的每一行减去该行的均值

#

## 练习题 - 解答


In [21]:
# @title 练习 1. 创建一个5×5的随机矩阵,计算它的转置和行列式

import torch

X = torch.rand(5, 5)
print("矩阵 X=", X)

# 矩阵的转置
X_t = X.T
print("矩阵 X 的转置 X.T=", X_t)

# 矩阵的行列式
X_det = X.det()
print("矩阵 X 的行列式 X.det()=", X_det)


矩阵 X= tensor([[0.8239, 0.4974, 0.9883, 0.8810, 0.5444],
        [0.6227, 0.8423, 0.0606, 0.0976, 0.2783],
        [0.0100, 0.5155, 0.9776, 0.7385, 0.8622],
        [0.8283, 0.6620, 0.7741, 0.5967, 0.7586],
        [0.0481, 0.5198, 0.6586, 0.1399, 0.3213]])
矩阵 X 的转置 X.T= tensor([[0.8239, 0.6227, 0.0100, 0.8283, 0.0481],
        [0.4974, 0.8423, 0.5155, 0.6620, 0.5198],
        [0.9883, 0.0606, 0.9776, 0.7741, 0.6586],
        [0.8810, 0.0976, 0.7385, 0.5967, 0.1399],
        [0.5444, 0.2783, 0.8622, 0.7586, 0.3213]])
矩阵 X 的行列式 X.det()= tensor(0.0815)


In [22]:
# @title 练习 2. 实现一个函数,将摄氏温度数组转换为华氏温度

## 方法 1：基础 Python（使用列表推导式）
def celsius_to_fahrenheit(celsius_list):
    """
    将摄氏度列表转换为华氏度列表
    公式: F = C * 9/5 + 32
    """
    return [round(c * 9/5 + 32, 2) for c in celsius_list]

# 测试
c_temps = [0, 25, 37, 100]
f_temps = celsius_to_fahrenheit(c_temps)
print(f"华氏温度: {f_temps}")
# 输出: [32.0, 77.0, 98.6, 212.0]



## 方法 2：使用 NumPy（适合大规模数据）
# 如果你处理的是大型数组，NumPy 的向量化操作速度会快得多，且代码最简洁。
import numpy as np

def convert_with_numpy(celsius_array):
    # 直接对整个数组进行数学运算
    c_arr = np.array(celsius_array)
    return c_arr * 9/5 + 32

# 测试
c_temps = [0, 25, 37, 100]
print(f"NumPy 转换结果: {convert_with_numpy(c_temps)}")



华氏温度: [32.0, 77.0, 98.6, 212.0]
NumPy 转换结果: [ 32.   77.   98.6 212. ]


In [23]:
# @title 练习 3. 创建包含更多行和列的数据集：
## 删除缺失值最多的列、将预处理后的数据集转换为张量格式

# 1. 创建大型数据集
# 使用 pandas 和 numpy 可以快速生成具有大量行和列的模拟数据，并随机插入缺失值。
import pandas as pd
import numpy as np
import torch

# 创建一个 1000 行 10 列的大型数据集
rows, cols = 1000, 10
data = np.random.randn(rows, cols)
df = pd.DataFrame(data, columns=[f'Col_{i}' for i in range(cols)])

# 随机插入一些缺失值 (NaN)
# 让 Col_3 成为缺失值最多的列
df.iloc[:500, 3] = np.nan
df.iloc[:100, 5] = np.nan


# 2. 删除缺失值最多的列
# 通过 isnull().sum() 计算每列的缺失值数量，找到最大值对应的索引并删除。
# 找到缺失值数量最多的列名
col_with_most_nan = df.isnull().sum().idxmax()
print(f"缺失值最多的列是: {col_with_most_nan}, 数量: {df[col_with_most_nan].isnull().sum()}")

# 删除该列
df_cleaned = df.drop(columns=[col_with_most_nan])


# 3. 将数据集转换为张量 (Tensor)
# 在转换之前，必须确保数据集中不再包含缺失值（因为 PyTorch 张量不支持在运算中包含 NaN，通常会导致梯度消失或报错）。一般采用均值填充或其他预处理。
# 3.1. 预处理：填充剩余的缺失值（例如用均值填充）
df_preprocessed = df_cleaned.fillna(df_cleaned.mean())

# 3.2. 转换为张量
# 使用 .values 获取 numpy 数组，再转为 tensor
# 推荐指定 dtype 为 float32，这是深度学习最常用的精度
data_tensor = torch.tensor(df_preprocessed.values, dtype=torch.float32)

print("张量形状:", data_tensor.shape)
print("前两行数据:\n", data_tensor[:2])


'''
关键步骤总结
1. isnull().sum(): 用于统计每列的缺失值分布。
2. drop(): 根据列名删除特定维度的数据。
3. fillna(): 在转换前必须处理掉所有 NaN，否则张量运算会出错。
4. torch.tensor(): 将处理好的 numpy 或 DataFrame 数组直接转换为 PyTorch 张量。
'''

缺失值最多的列是: Col_3, 数量: 500
张量形状: torch.Size([1000, 9])
前两行数据:
 tensor([[-0.6880,  2.2629, -0.8813, -0.7771,  0.0197,  0.4651,  0.1003, -1.1957,
         -0.4080],
        [-0.6215,  1.8709,  0.2080,  0.6547,  0.0197,  1.0439, -0.6895, -0.4474,
          1.8099]])


'\n关键步骤总结\n1. isnull().sum(): 用于统计每列的缺失值分布。\n2. drop(): 根据列名删除特定维度的数据。\n3. fillna(): 在转换前必须处理掉所有 NaN，否则张量运算会出错。\n4. torch.tensor(): 将处理好的 numpy 或 DataFrame 数组直接转换为 PyTorch 张量。 \n'

In [28]:
# @title 练习 4. 尝试使用广播机制,对一个矩阵的每一行减去该行的均值
import torch

X = torch.arange(12, dtype=float).reshape(3, 4)
print("矩阵 X: ", X)

# 2. 计算每一行的均值
# dim=1 表示跨列计算（即对每一行求均值）
# keepdim=True 是关键：它将结果形状从 [3] 变为 [3, 1]
row_means = X.mean(dim=1, keepdim=True)
print("\n每行的均值 (形状 [3, 1]):\n", row_means)

# 3. 利用广播机制进行减法
# X 的形状是 [3, 4]，row_means 的形状是 [3, 1]
# 广播机制会自动将 [3, 1] 扩展为 [3, 4] 以匹配 X
X_centered = X - row_means

print("\n减去行均值后的结果:\n", X_centered)

# 验证：现在每一行的和（或均值）应该接近 0
print("\n验证（每行求和）:\n", X_centered.sum(dim=1))

矩阵 X:  tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]], dtype=torch.float64)

每行的均值 (形状 [3, 1]):
 tensor([[1.5000],
        [5.5000],
        [9.5000]], dtype=torch.float64)

减去行均值后的结果:
 tensor([[-1.5000, -0.5000,  0.5000,  1.5000],
        [-1.5000, -0.5000,  0.5000,  1.5000],
        [-1.5000, -0.5000,  0.5000,  1.5000]], dtype=torch.float64)

验证（每行求和）:
 tensor([0., 0., 0.], dtype=torch.float64)
